//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppEval.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:sioservice", ConfigurationName="ServiceReference1.sioservicePort")]
    public interface sioservicePort {
        
        [System.ServiceModel.OperationContractAttribute(Action="connectAction", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="status")]
        string connect(string login, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="connectAction", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="status")]
        System.Threading.Tasks.Task<string> connectAsync(string login, string password);
        
        // CODEGEN : La génération du contrat de message depuis l'espace de noms de wrapper (urn:Easyservice) du message exportOffreListRequest ne correspond pas à la valeur par défaut (urn:sioservice)
        [System.ServiceModel.OperationContractAttribute(Action="exportOffreListAction", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        AppEval.ServiceReference1.exportOffreListResponse exportOffreList(AppEval.ServiceReference1.exportOffreListRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="exportOffreListAction", ReplyAction="*")]
        System.Threading.Tasks.Task<AppEval.ServiceReference1.exportOffreListResponse> exportOffreListAsync(AppEval.ServiceReference1.exportOffreListRequest request);
        
        // CODEGEN : La génération du contrat de message depuis l'espace de noms de wrapper (urn:Easyservice) du message exportCandidatureListRequest ne correspond pas à la valeur par défaut (urn:sioservice)
        [System.ServiceModel.OperationContractAttribute(Action="exportCandidatureListAction", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        AppEval.ServiceReference1.exportCandidatureListResponse exportCandidatureList(AppEval.ServiceReference1.exportCandidatureListRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="exportCandidatureListAction", ReplyAction="*")]
        System.Threading.Tasks.Task<AppEval.ServiceReference1.exportCandidatureListResponse> exportCandidatureListAsync(AppEval.ServiceReference1.exportCandidatureListRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="exportOffreList", WrapperNamespace="urn:Easyservice", IsWrapped=true)]
    public partial class exportOffreListRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        [System.Xml.Serialization.SoapElementAttribute(DataType="integer")]
        public string id;
        
        public exportOffreListRequest() {
        }
        
        public exportOffreListRequest(string id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="exportOffreListResponse", WrapperNamespace="urn:Easyservice", IsWrapped=true)]
    public partial class exportOffreListResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string xml;
        
        public exportOffreListResponse() {
        }
        
        public exportOffreListResponse(string xml) {
            this.xml = xml;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="exportCandidatureList", WrapperNamespace="urn:Easyservice", IsWrapped=true)]
    public partial class exportCandidatureListRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        [System.Xml.Serialization.SoapElementAttribute(DataType="integer")]
        public string id;
        
        public exportCandidatureListRequest() {
        }
        
        public exportCandidatureListRequest(string id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="exportCandidatureListResponse", WrapperNamespace="urn:Easyservice", IsWrapped=true)]
    public partial class exportCandidatureListResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string xml;
        
        public exportCandidatureListResponse() {
        }
        
        public exportCandidatureListResponse(string xml) {
            this.xml = xml;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface sioservicePortChannel : AppEval.ServiceReference1.sioservicePort, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class sioservicePortClient : System.ServiceModel.ClientBase<AppEval.ServiceReference1.sioservicePort>, AppEval.ServiceReference1.sioservicePort {
        
        public sioservicePortClient() {
        }
        
        public sioservicePortClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public sioservicePortClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public sioservicePortClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public sioservicePortClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string connect(string login, string password) {
            return base.Channel.connect(login, password);
        }
        
        public System.Threading.Tasks.Task<string> connectAsync(string login, string password) {
            return base.Channel.connectAsync(login, password);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AppEval.ServiceReference1.exportOffreListResponse AppEval.ServiceReference1.sioservicePort.exportOffreList(AppEval.ServiceReference1.exportOffreListRequest request) {
            return base.Channel.exportOffreList(request);
        }
        
        public string exportOffreList(string id) {
            AppEval.ServiceReference1.exportOffreListRequest inValue = new AppEval.ServiceReference1.exportOffreListRequest();
            inValue.id = id;
            AppEval.ServiceReference1.exportOffreListResponse retVal = ((AppEval.ServiceReference1.sioservicePort)(this)).exportOffreList(inValue);
            return retVal.xml;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AppEval.ServiceReference1.exportOffreListResponse> AppEval.ServiceReference1.sioservicePort.exportOffreListAsync(AppEval.ServiceReference1.exportOffreListRequest request) {
            return base.Channel.exportOffreListAsync(request);
        }
        
        public System.Threading.Tasks.Task<AppEval.ServiceReference1.exportOffreListResponse> exportOffreListAsync(string id) {
            AppEval.ServiceReference1.exportOffreListRequest inValue = new AppEval.ServiceReference1.exportOffreListRequest();
            inValue.id = id;
            return ((AppEval.ServiceReference1.sioservicePort)(this)).exportOffreListAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AppEval.ServiceReference1.exportCandidatureListResponse AppEval.ServiceReference1.sioservicePort.exportCandidatureList(AppEval.ServiceReference1.exportCandidatureListRequest request) {
            return base.Channel.exportCandidatureList(request);
        }
        
        public string exportCandidatureList(string id) {
            AppEval.ServiceReference1.exportCandidatureListRequest inValue = new AppEval.ServiceReference1.exportCandidatureListRequest();
            inValue.id = id;
            AppEval.ServiceReference1.exportCandidatureListResponse retVal = ((AppEval.ServiceReference1.sioservicePort)(this)).exportCandidatureList(inValue);
            return retVal.xml;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AppEval.ServiceReference1.exportCandidatureListResponse> AppEval.ServiceReference1.sioservicePort.exportCandidatureListAsync(AppEval.ServiceReference1.exportCandidatureListRequest request) {
            return base.Channel.exportCandidatureListAsync(request);
        }
        
        public System.Threading.Tasks.Task<AppEval.ServiceReference1.exportCandidatureListResponse> exportCandidatureListAsync(string id) {
            AppEval.ServiceReference1.exportCandidatureListRequest inValue = new AppEval.ServiceReference1.exportCandidatureListRequest();
            inValue.id = id;
            return ((AppEval.ServiceReference1.sioservicePort)(this)).exportCandidatureListAsync(inValue);
        }
    }
}
